import { ROLES } from './roles';

export const PERMISSIONS = {
  VIEW_DASHBOARD: 'view_dashboard',
  MANAGE_CATEGORIES: 'manage_categories',
  MANAGE_PRODUCTS: 'manage_products',
  MANAGE_ORDERS: 'manage_orders',
  UPDATE_ORDER_STATUS: 'update_order_status',
  VIEW_USERS: 'view_users',
  MANAGE_USERS: 'manage_users',
  MANAGE_MEDIA: 'manage_media',
  VIEW_ANALYTICS: 'view_analytics',
  MANAGE_STAFF: 'manage_staff',
  VIEW_LOGS: 'view_logs',
  MANAGE_CONFIG: 'manage_config',
  MANAGE_MAINTENANCE: 'manage_maintenance',
};

export const ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  'ADMIN': Object.values(PERMISSIONS),
  
  [ROLES.PRODUCT_MANAGER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.MANAGE_CATEGORIES,
    PERMISSIONS.MANAGE_PRODUCTS,
    PERMISSIONS.MANAGE_MEDIA,
    PERMISSIONS.MANAGE_CONFIG,
    PERMISSIONS.MANAGE_MAINTENANCE,
  ],
  
  [ROLES.SUPPORT_STAFF]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.MANAGE_ORDERS,
    PERMISSIONS.UPDATE_ORDER_STATUS,
    PERMISSIONS.VIEW_USERS,
  ],
  
  [ROLES.ORDER_MANAGER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.MANAGE_ORDERS,
    PERMISSIONS.UPDATE_ORDER_STATUS,
  ],
  
  [ROLES.ANALYTICS_MANAGER]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_ANALYTICS,
  ]
};
