export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  PRODUCT_MANAGER: 'PRODUCT_MANAGER',
  SUPPORT_STAFF: 'SUPPORT_STAFF',
  ORDER_MANAGER: 'ORDER_MANAGER',
  ANALYTICS_MANAGER: 'ANALYTICS_MANAGER'
};
